# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Creator.Infinity.Json Nuget package (Test Environment)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Verify Tag
        id: check-tag
        run: |
          if [[ ${{ github.ref_name }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag found..."
          else
            echo "No git tag found, action cancelled..."
            exit 1
          fi

      - name: Restore dependencies
        run: dotnet restore ./Creator.Infinity.Json/Creator.Infinity.Json.csproj

      - name: Build project
        run: dotnet build --no-restore -c release ./Creator.Infinity.Json/Creator.Infinity.Json.csproj

      - name: Test project
        run: dotnet test --verbosity normal ./Creator.Infinity.Json.Test/Creator.Infinity.Json.Test.csproj

      - name: publish project
        run: dotnet publish --no-build -c release -o ./publish ./Creator.Infinity.Json/Creator.Infinity.Json.csproj

      - name: Create NuGet Package
        run: dotnet pack -c release -o ./nuget-publish ./Creator.Infinity.Json/Creator.Infinity.Json.csproj /p:Version=${{ github.ref_name }} /p:PackageReleaseNotes="See https://github.com/TheCreatorGanesh/Github-Experiments/releases/tag/${{ github.ref_name }}"

      - name: Publish Nuget Package
        run: dotnet nuget push ./nuget-publish/*.nupkg --api-key ${{ secrets.nuget_api_key_test }} --source https://apiint.nugettest.org/v3/index.json --no-symbols --skip-duplicate
